export const quizAvailable = {
  number_of_attempts: 1,
  check_correctness_instantly: false,
  is_sequential: false,
  result_on_submission: false,
  _id: '619771ed10b2a12ef1c7bed8',
  quiz_name: 'demo12',
  quiz_start_date: '2019-04-28T09:15:15.000Z',
  quiz_end_date: '2019-04-28T09:15:15.000Z',
  total_questions: 30,
  questions: [
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: 'http://source.unsplash.com/random',
      answer: 1,
      options: [
        {
          optionUrl: 'http://source.unsplash.com/random',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
    {
      qsMandatory: true,
      qsHint: 'No hints for this question',
      qsImageUrl: '',
      answer: 1,
      options: [
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7bedb',
          optionText: 'option A',
        },
        {
          optionUrl: '',
          _id: '619771ed10b2a12ef1c7beda',
          optionText: 'option B',
        },
      ],
      _id: '619771ed10b2a12ef1c7bed9',
      qsType: 'single',
      qsText: 'What is answer?',
    },
  ],
  createdAt: '2021-11-19T09:44:13.138Z',
  updatedAt: '2021-11-19T09:44:13.138Z',
  __v: 0,
};
